/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Carrousel: typeof import('./src/components/products/Carrousel.vue')['default']
    FooterComponent: typeof import('./src/components/shared/FooterComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    NavbarComponent: typeof import('./src/components/shared/NavbarComponent.vue')['default']
    ProductCard: typeof import('./src/components/products/ProductCard.vue')['default']
    ProductCarrousel: typeof import('./src/components/products/ProductCarrousel.vue')['default']
    ProductListCard: typeof import('./src/components/products/ProductListCard.vue')['default']
    ProductSelect: typeof import('./src/components/products/ProductSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
